### ISSUE TITLE
mongo-mock update

### ISSUE THREAD

**Issue by BoLaMN** [devetry/mongo-schemer#6]
hey guys 

ive also got a branch ready that removes the objectid to string workaround by updating to the latest version of mongo-mock, the tests pass but im not sure if theres other concerns that i should be looking for? [https://github.com/BoLaMN/mongo-schemer/tree/mongo-mock-upgrade](https://github.com/BoLaMN/mongo-schemer/tree/mongo-mock-upgrade)

cheers

**Comment by bgschiller** [comment]
If the tests pass, I'd say we're safe. Feel free to submit another PR.

It seems like this is a project you're interested in-- would you want to be
made a contributor?

-Brian

**Comment by bgschiller** [comment]
@BoLaMN I noticed that there were some vulnerability warnings on npm install, one of which was mongo-mock. I went ahead and merged your branch, as well as upgrading a couple other deps.

This, along with your other branch is now published as 1.0.4 🎉
